added encoded the SSH key

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -78,7 +78,7 @@ jobs:
 
       - name: Save SSH Key
         run: |
-          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > key.pem
+          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > key.pem || echo "Failed to decode key"
           chmod 600 key.pem
 
       - name: Deploy to EC2 via SSH
